/*
 * This source file was generated by the Gradle 'init' task
 */
// package forgevoxel;

// import org.junit.jupiter.api.Test;

// import com.example.App;

// import static org.junit.jupiter.api.Assertions.*;

// class AppTest {
//     @Test void appHasAGreeting() {
//         App classUnderTest = new App();
//     }
// }
