/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example;

import java.util.List;
import java.util.concurrent.Future;

import org.lwjgl.glfw.GLFW;

import com.example.TextEditor.Interpreter.CodeEditorUI;
import com.example.TextEditor.Interpreter.interpreter.RuntimeError;
import com.example.io.PuzzelLevel;
import com.example.shape.Gizmo;
import com.example.shape.GizmoState;
import com.example.shape.OrbitCamera;
import com.example.shape.Puzzel;
import com.example.shape.Voxel;

import com.jme3.app.SimpleApplication;
import com.jme3.asset.plugins.FileLocator;
import com.jme3.light.AmbientLight;
import com.jme3.light.DirectionalLight;
import com.jme3.material.Material;
import com.jme3.math.ColorRGBA;
import com.jme3.math.Vector3f;
import com.jme3.renderer.Camera;
import com.jme3.renderer.ViewPort;
import com.jme3.scene.Geometry;
import com.jme3.scene.Node;
import com.jme3.scene.shape.Quad;
import com.jme3.shadow.DirectionalLightShadowRenderer;
import com.jme3.shadow.EdgeFilteringMode;
import com.jme3.system.lwjgl.LwjglWindow;

import javafx.application.Platform;

public class App extends SimpleApplication{
    public String getGreeting() {
        return "Hello World!";
    }

    @Override
    public void stop() {
        super.stop();
        MainMenu.levelIO.updateUserCode(codeEditorUI.getCode(), puzzelLevel);
        MainMenu.levelIO.writeLastPlayedLevel(puzzelLevel.levelName, puzzelNumber);

        Platform.runLater(() -> { if(codeEditorUI != null){codeEditorUI.close();} });
        MainMenu.jmeThread = null;
        MainMenu.app = null;
    }

    @Override
    public void destroy() {
        super.destroy();
        MainMenu.levelIO.updateUserCode(codeEditorUI.getCode(), puzzelLevel);
        MainMenu.levelIO.writeLastPlayedLevel(puzzelLevel.levelName, puzzelNumber);
        
        Platform.runLater(() -> { if(codeEditorUI != null){codeEditorUI.close();} });
        MainMenu.jmeThread = null;
        MainMenu.app = null;
    }

    // public static void main(String[] args) {
    //     javafx.application.Platform.startup(() -> {});

    //     App app = new App();
    //     app.start();
    // }

    // code Editor
    private CodeEditorUI codeEditorUI;
    private LevelSelectionUI levelSelectionUI;

    private Camera topCam;
    private Camera bottomCam;
    private Node topRootNode;
    private Node bottomRootNode;
    private OrbitCamera topOrbitCamera;
    private OrbitCamera bottomOrbitCamera;
    private Gizmo topGizmo;
    private Gizmo bottomGizmo;

    private Future<?> errorCheck = null;
    public PuzzelLevel puzzelLevel;
    private Puzzel puzzel;
    public int puzzelNumber;

    public App(PuzzelLevel puzzelLevel, int puzzelNumber, LevelSelectionUI levelSelectionUI){
        super();
        this.puzzelLevel = puzzelLevel;
        this.puzzelNumber = puzzelNumber;
        this.levelSelectionUI = levelSelectionUI;
    }

    @Override
    public void simpleInitApp() {
        assetManager.registerLocator("assets/", FileLocator.class);
        Voxel.setAssetManager(assetManager);

        puzzel = puzzelLevel.toPuzzel(this);

        viewPort.setBackgroundColor(ColorRGBA.fromRGBA255(3 ,3, 3, 255));
        flyCam.setEnabled(false);
        inputManager.setCursorVisible(true);
        setPauseOnLostFocus(false);

        // stacking two screens
        topRootNode = new Node("top");
        bottomRootNode = new Node("bottom");

        topCam = cam.clone();
        topCam.setLocation(new Vector3f(0, 0, 5));
        topCam.lookAt(Vector3f.ZERO, Vector3f.UNIT_Y);
        topCam.setViewPort(0.5f, 1f, 0.5f, 1f);

        ViewPort topViewPort = renderManager.createMainView("TopViewPort", topCam);
        topViewPort.setBackgroundColor(ColorRGBA.fromRGBA255(2 ,2, 2, 255).mult(1.15f));
        topViewPort.setClearFlags(true, true, true);
        topViewPort.attachScene(topRootNode);

        bottomCam = cam.clone();
        bottomCam.setLocation(new Vector3f(0, 0, 5));
        bottomCam.lookAt(Vector3f.ZERO, Vector3f.UNIT_Y);
        bottomCam.setViewPort(0.5f, 1f, 0f, 0.5f);

        ViewPort bottomViewPort = renderManager.createMainView("BottomViewPort", bottomCam);
        bottomViewPort.setBackgroundColor(ColorRGBA.fromRGBA255(2 ,2, 2, 255).mult(1.15f));
        bottomViewPort.setClearFlags(true, true, true);
        bottomViewPort.attachScene(bottomRootNode);

        // making lights
        DirectionalLight topSun = new DirectionalLight();
        topSun.setDirection(new Vector3f(-1, -0.33f, -1).normalizeLocal());
        topSun.setColor(ColorRGBA.White.mult(1.5f));

        AmbientLight topAmbientLight = new AmbientLight();
        topAmbientLight.setColor(ColorRGBA.White.mult(0.4f));

        topRootNode.addLight(topSun);
        topRootNode.addLight(topAmbientLight);

        DirectionalLight bottomSun = new DirectionalLight();
        bottomSun.setDirection(new Vector3f(-1f, -0.333f, -1f).normalizeLocal());
        bottomSun.setColor(ColorRGBA.White.mult(1.5f));

        AmbientLight bottomAmbientLight = new AmbientLight();
        bottomAmbientLight.setColor(ColorRGBA.White.mult(0.4f));

        bottomRootNode.addLight(bottomSun);
        bottomRootNode.addLight(bottomAmbientLight);

        // making shadow
        DirectionalLightShadowRenderer topShadowRenderer = new DirectionalLightShadowRenderer(assetManager, 2048, 3);
        topShadowRenderer.setShadowZExtend(50f);
        topShadowRenderer.setLight(topSun);
        topShadowRenderer.setShadowIntensity(0.4f);
        topShadowRenderer.setEdgeFilteringMode(EdgeFilteringMode.Bilinear);

        topViewPort.addProcessor(topShadowRenderer);

        DirectionalLightShadowRenderer bottomShadowRenderer = new DirectionalLightShadowRenderer(assetManager, 2048, 3);
        bottomShadowRenderer.setShadowZExtend(50f);
        bottomShadowRenderer.setLight(bottomSun);
        bottomShadowRenderer.setShadowIntensity(0.4f);
        bottomShadowRenderer.setEdgeFilteringMode(EdgeFilteringMode.Bilinear);

        bottomViewPort.addProcessor(bottomShadowRenderer);

        addBorder(0.5f, 1f, 0.5f, 1f , 8, 6, ColorRGBA.fromRGBA255(50, 50, 50, 255), ColorRGBA.fromRGBA255(144, 164, 174, 255));
        addBorder(0.5f, 1f, 0f, 0.5f , 8, 6, ColorRGBA.fromRGBA255(50, 50, 50, 255), ColorRGBA.fromRGBA255(144, 164, 174, 255));
        
        GizmoState sharedGizmoState = new GizmoState(puzzel.getWidth() / 2 + 1, puzzel.getHeight() / 2 + 1, puzzel.getDepth() / 2 + 1);
        
        topOrbitCamera = new OrbitCamera(topRootNode, topCam, this, inputManager, assetManager);
        topGizmo = new Gizmo(puzzel.getUserGrid(), inputManager, topCam, sharedGizmoState);
        topGizmo.intializeAxisBars(assetManager);
        puzzel.getUserGrid().addGizmo(topGizmo);
        
        bottomOrbitCamera = new OrbitCamera(bottomRootNode, bottomCam, this, inputManager, assetManager);
        bottomGizmo = new Gizmo(puzzel.getTargetGrid(), inputManager, bottomCam, sharedGizmoState);
        bottomGizmo.intializeAxisBars(assetManager);
        puzzel.getTargetGrid().addGizmo(bottomGizmo);
        
        this.enqueue(() -> {
            puzzel.intializeTargetGrid(bottomRootNode, this);
            puzzel.intializeUserGrid(topRootNode);

            if(!puzzelLevel.userFunction.isBlank()){
                runCode(puzzelLevel.userFunction);
            }
        });

        codeEditorUI = new CodeEditorUI(this);
        Platform.runLater(
            () -> { 
                codeEditorUI.intializeUI();
                if(!puzzelLevel.userFunction.isBlank()){
                    codeEditorUI.setCode(puzzelLevel.userFunction);
                } 
            }
        );

        long windowHandle = ((LwjglWindow)getContext()).getWindowHandle();
        GLFW.glfwSetWindowPosCallback(windowHandle, 
            (window, xpos, ypos) -> { Platform.runLater( () -> { codeEditorUI.updatePosition(xpos, ypos); } ); }
        );
    }

    @Override
    public void simpleUpdate(float tpf) {
        topRootNode.updateLogicalState(tpf);
        topRootNode.updateGeometricState();

        bottomRootNode.updateLogicalState(tpf);
        bottomRootNode.updateGeometricState();

        if (errorCheck != null && errorCheck.isDone()) {
            try { errorCheck.get(); } 
            catch (RuntimeError e) { Platform.runLater(() -> codeEditorUI.updateErrorDisplay(e.getMessage()) ); }
            catch (Exception e) { Platform.runLater(() -> codeEditorUI.updateErrorDisplay(e.getMessage()) ); }

            errorCheck = null;
        }

        this.enqueue(
            () -> {
                topOrbitCamera.mouseHoverCheck();
                topGizmo.updateSelector();

                bottomOrbitCamera.mouseHoverCheck();
                bottomGizmo.updateSelector();
            }
        );
    }

    @Override
    public void reshape(int w, int h) {
        Platform.runLater( () -> { if(codeEditorUI != null) { codeEditorUI.updateSize(w, h); } } );
    }

    private void addBorder(float x1, float x2, float y1, float y2, float thickness, float centerThickness, ColorRGBA color, ColorRGBA centerColor) {
        float screenWidth = settings.getWindowWidth();
        float screenHeight = settings.getWindowHeight();

        float x1Screen = x1 * screenWidth;
        float y1Screen = y1 * screenHeight; 
        float x2Screen = x2 * screenWidth;
        float y2Screen = y2 * screenHeight; 
        
        float width = x2Screen - x1Screen;
        float height = y2Screen - y1Screen; 

        float deltaThickness = thickness - centerThickness;
        float centerWidth = width - deltaThickness;
        float centerHeight = height - deltaThickness;

        float topY = y2Screen - thickness;
        float rightX = x2Screen - thickness;

        Geometry topBar = new Geometry("topBar", new Quad(width, thickness));
        Geometry rightBar = new Geometry("rightBar", new Quad(thickness, height));
        Geometry bottomBar = new Geometry("bottomBar", new Quad(width, thickness));
        Geometry leftBar = new Geometry("leftBar", new Quad(thickness, height));

        topBar.setLocalTranslation(x1Screen, topY, 0);
        rightBar.setLocalTranslation(x2Screen - thickness, y1Screen, 0);
        bottomBar.setLocalTranslation(x1Screen, y1Screen, 0);
        leftBar.setLocalTranslation(x1Screen, y1Screen, 0);

        Material material = new Material(assetManager, "Common/MatDefs/Misc/Unshaded.j3md");
        material.setColor("Color", color);

        for(Geometry bar : List.of(topBar, rightBar, bottomBar, leftBar)){
            bar.setMaterial(material);
            guiNode.attachChild(bar);
        }

        Geometry topCenterBar = new Geometry("topCenterBar", new Quad(centerWidth, centerThickness));
        Geometry rightCenterBar = new Geometry("rightCenterBar", new Quad(centerThickness, centerHeight));
        Geometry bottomCenterBar = new Geometry("bottomCenterBar", new Quad(centerWidth, centerThickness));
        Geometry leftCenterBar = new Geometry("leftCenterBar", new Quad(centerThickness, centerHeight));

        float centerOffset = deltaThickness / 2;

        topCenterBar.setLocalTranslation(x1Screen + centerOffset, topY + centerOffset, 0);
        rightCenterBar.setLocalTranslation(rightX + centerOffset, y1Screen + centerOffset, 0);
        bottomCenterBar.setLocalTranslation(x1Screen + centerOffset, y1Screen + centerOffset, 0);
        leftCenterBar.setLocalTranslation(x1Screen + centerOffset, y1Screen + centerOffset, 0);

        Material materialCenter = new Material(assetManager, "Common/MatDefs/Misc/Unshaded.j3md");
        materialCenter.setColor("Color", centerColor);

        for(Geometry bar : List.of(topCenterBar, rightCenterBar, bottomCenterBar, leftCenterBar)){
            bar.setMaterial(materialCenter);
            guiNode.attachChild(bar);
        }
    }

    public void runCode(String newCode){
        errorCheck = this.enqueue(
            () -> { 
                try {
                    puzzel.updateUserGrid(newCode, this);

                    Platform.runLater(
                        () -> {
                            codeEditorUI.updateErrorDisplay("");
                           codeEditorUI.setMatchingPercentage(puzzel.getMatchPercentage());
                        }
                    );
                    if(puzzel.isComplete()){
                        Platform.runLater(
                            () -> {
                                codeEditorUI.setPuzzelCompleted();
                                levelSelectionUI.setLevelComplted(puzzelNumber);
                            }
                        );
                        MainMenu.levelIO.updateCompletion(true, puzzelLevel);
                        puzzelLevel.completed = true;
                    }
                } 
                catch (RuntimeError r) { codeEditorUI.updateErrorDisplay(r.getMessage()); } 
                catch (Exception e) { codeEditorUI.updateErrorDisplay("Syntax Error: " + e.getMessage());}
                return null;
            }
        );
    }

    public void nextLevel(PuzzelLevel level, int number) {
        this.puzzelLevel = level;
        this.puzzelNumber = number;

        Node topOrbitNode = topOrbitCamera.getOrbitCameraNode();
        Node botttomOrbitNode = bottomOrbitCamera.getOrbitCameraNode();

        topRootNode.detachAllChildren();
        bottomRootNode.detachAllChildren();

        topRootNode.attachChild(topOrbitNode);
        bottomRootNode.attachChild(botttomOrbitNode);

        puzzel = puzzelLevel.toPuzzel(this);

        GizmoState sharedState = new GizmoState(
            puzzel.getWidth() / 2 + 1,
            puzzel.getHeight() / 2 + 1,
            puzzel.getDepth() / 2 + 1
        );

        topGizmo = new Gizmo(puzzel.getUserGrid(), inputManager, topCam, sharedState);
        topGizmo.intializeAxisBars(assetManager);
        puzzel.getUserGrid().addGizmo(topGizmo);

        bottomGizmo = new Gizmo(puzzel.getTargetGrid(), inputManager, bottomCam, sharedState);
        bottomGizmo.intializeAxisBars(assetManager);
        puzzel.getTargetGrid().addGizmo(bottomGizmo);

        this.enqueue(
            () -> {
                puzzel.intializeTargetGrid(bottomRootNode, this);
                puzzel.intializeUserGrid(topRootNode);
                return null;
            }
        );

        Platform.runLater(() -> codeEditorUI.reset());
    }

	public void codeEditorUiGeomDisplay(String name) {
        codeEditorUI.updateGeomDisplay(name);
	}

    public void codeEditorUiGeomDisplayReset(){
        codeEditorUI.resetGeomDisplay();
    }
}
