package TextEditor.Interpreter.statements;

public enum StatementType {
    IDENTIFIER,
    BOOLEAN_LITERAL,
    NUMERIC_LITERAL,
    NULL_LITERAL,
    BINARY_EXPRESSION,
    UNARY_EXPRESSION,
    IF_STATEMENT,
    WHILE_STATEMENT,
    BLOCK_STATEMENT,
    RETURN_STATEMENT,
    VAR_DECLARATION,
    ASSIGNMENT_EXPRESSION,
    CALL_EXPRESSION,
    FUNCTION_DECLARATION,
    TUPLE_LITERAL;
}
